### ISSUE TITLE
A question about ablation studies in Table 2.

### ISSUE THREAD

**Issue by bad-meets-joke** [shiming-chen/MSDN#10]
Hi, 

I have a question about the ablation studies in Table 2.

Why can a single subnet, e.g. MSDN (A->V) w/ L_distill, be trained with semantic distillation loss that calculates the difference between two subnet outputs?

Looking forward to your reply soon.

**Comment by shiming-chen** [comment]
Hi, @bad-meets-joke 

In Table 2, MSDN(A->V) w/L_distill means that the MSDN  trained with L_distill loss, but we only take the features in A->V branch for  classification. Please refer to the related descirptions in the paper.

Best!

**Comment by bad-meets-joke** [comment]
Thanks for your reply. Now I get it.
